apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
  namespace: anythingllm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      containers:
        - name: ollama
          image: ollama/ollama:latest
          securityContext:
            runAsUser: 0   # nécessaire car Ollama écrit dans /root/.ollama
          ports:
            - containerPort: 11434
          volumeMounts:
            - name: ollama-models
              mountPath: /root/.ollama
      volumes:
        - name: ollama-models
          persistentVolumeClaim:
            claimName: pvc-ollama
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-ollama
  namespace: anythingllm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: Service
metadata:
  name: ollama
  namespace: anythingllm
spec:
  selector:
    app: ollama
  ports:
    - port: 11434
      targetPort: 11434
      protocol: TCP
