apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-postgres
  labels:
    name: pv-postgres
spec:
  storageClassName: standard
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /data/nfs/anythingllm/postgres
    server: 192.168.1.54
    readOnly: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-anythingllm
  labels:
    name: pv-anythingllm
spec:
  storageClassName: standard
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /data/nfs/anythingllm/anythingllm
    server: 192.168.1.54
    readOnly: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-ollama
  labels:
    name: pv-ollama
spec:
  storageClassName: standard
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /data/nfs/anythingllm/ollama
    server: 192.168.1.54
    readOnly: false

