apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-postgres
  namespace: anythingllm
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: pv-postgres
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-anythingllm
  namespace: anythingllm
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: pv-anythingllm
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-ollama
  namespace: anythingllm
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: pv-ollama
