apiVersion: v1
kind: PersistentVolume
metadata:
  name: qdrant-nfs-pv
spec:
  storageClassName: qdrant-nfs
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany   # NFS supporte RWX
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /data/nfs/qdrant
    server: 192.168.1.54
    readOnly: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: qdrant-nfs-pv-0
spec:
  storageClassName: qdrant-nfs
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /data/nfs/qdrant/0
    server: 192.168.1.54
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: qdrant-nfs-pv-1
spec:
  storageClassName: qdrant-nfs
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /data/nfs/qdrant/1
    server: 192.168.1.54
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: qdrant-nfs-pv-2
spec:
  storageClassName: qdrant-nfs
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /data/nfs/qdrant/2
    server: 192.168.1.54
