apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qdrant-nfs-pvc
  namespace: qdrant
spec:
  storageClassName: qdrant-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: qdrant-nfs-pv

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qdrant-storage-qdrant-0
  namespace: qdrant
spec:
  storageClassName: qdrant-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: qdrant-nfs-pv-0
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qdrant-storage-qdrant-1
  namespace: qdrant
spec:
  storageClassName: qdrant-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: qdrant-nfs-pv-1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qdrant-storage-qdrant-2
  namespace: qdrant
spec:
  storageClassName: qdrant-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: qdrant-nfs-pv-2
