apiVersion: v1
kind: PersistentVolume
metadata:
  name: n8n-pv
spec:
  storageClassName: standard
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /data/nfs/n8n
    server: 192.168.1.54
    readOnly: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: n8n-pv-postgres
spec:
  storageClassName: standard
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /data/nfs/n8n/postgres
    server: 192.168.1.54
    readOnly: false
---