apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-whisper
  labels:
    name: pv-whisper
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /data/nfs/whisper
    server: 192.168.1.54
    readOnly: false