apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: whisper-cache-pvc
  namespace: whisper
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-whisper